"""The agent's output contract and its Validator layer (generated by genproj).

`output_type` is a Pydantic model, not free text and not YAML: a typed model is
what buys validation and a retry loop. Render any wire format (YAML, Markdown)
from the model in code; asking the model for it buys nothing and loses the
typing.

`validate_agent_result` is the Validator layer. It runs on every model output
and raises `ModelRetry` with real error text to make the model repair its answer,
up to `retries["output"]` in agent/main.py. Wire it to a real oracle (a
validator service, an API that prices the request) rather than rebuilding the
check in-process - only the API is the oracle for a money gate. When the retry
budget is exhausted the run fails loudly; do not swallow it.

This is a SHELL. Replace the placeholder model and check with the domain's own.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from pydantic_ai import ModelRetry, RunContext


class AgentResult(BaseModel):
    """The agent's typed answer.

    Replace this with the real output type - e.g. a ticket (a Pydantic model)
    whose fields the Validator can check against an API.
    """

    summary: str = Field(description="A one-line summary of the answer.")
    details: dict = Field(
        default_factory=dict,
        description="Structured detail for the answer; schema owned by the domain.",
    )


async def validate_agent_result(
    _ctx: RunContext, output: AgentResult
) -> AgentResult:
    """Reject an output the domain cannot accept, and say why.

    A placeholder check: it only refuses an empty summary. Replace the body with
    a real validation - call the validator service, price the request - and raise
    `ModelRetry(<the service's own error text>)` so the model can fix it. Raise
    nothing else, and never swallow exhaustion.
    """
    if not output.summary.strip():
        raise ModelRetry(
            "The result summary was empty. Produce a non-empty summary."
        )
    return output
