// tests/generator/docker-external-networks.test.js

/**
 * Spec 018: `docker-container.externalNetworks` attaches a generated container
 * to one or more named, pre-existing external Docker networks (e.g. MCPHub's
 * `ai_proxy`). These tests pin the three things the feature must not get wrong:
 *
 * 1. Strictly additive: the empty/default case is byte-identical to before.
 * 2. The emission is the service attachment + the top-level `external: true`
 *    declaration, and it is valid YAML.
 * 3. `networkMode: host` + external networks is rejected loudly, and never
 *    emitted as an invalid compose file even on a path that skips the guards.
 */

import { describe, it, expect } from "vitest";
import { generateAllFiles } from "../../src/generator/file-generator.js";
import { getCapabilityTemplateData } from "../../src/generator/capability-template-utils.js";
import { validateDockerNetworks } from "../../src/generator/project-validation.js";
import { ValidationError } from "../../src/generator/genproj-errors.js";

// The round-1 verification config (memo 018): the NAS project that must join
// `ai_proxy`. Bridge mode, a published port and one env var, so the whole
// compose body is exercised.
const BASE_CONFIG = {
  networkMode: "bridge",
  exposePort: 8772,
  publishPort: "0.0.0.0:8772:8772",
  hostname: "nas",
  healthcheck: "http:/health",
  envVars: ["DATABENTO_API_KEY"],
};

const generate = (dockerConfig = {}) =>
  generateAllFiles({
    name: "databento-discovery-mcp",
    capabilities: [
      "devcontainer-python",
      "docker-container",
      "buildkite",
      "dependabot",
    ],
    configuration: { "docker-container": { ...BASE_CONFIG, ...dockerConfig } },
  });

const byPath = (files, filePath) =>
  files.find((file) => file.filePath === filePath);

// The exact compose a docker-container project emitted before this feature.
// Kept literal on purpose: the requirement is byte-identity, and a helper that
// derives the expectation from the generator cannot prove it.
const BASELINE_COMPOSE = [
  "# Docker Compose configuration for databento-discovery-mcp",
  "# Generated by genproj (docker-container capability).",
  "#",
  "# Deploy with: docker compose up -d",
  '# (On Synology, import this file as a Container Manager "Project".)',
  "#",
  "# The image reference uses your registry namespace (GitHub username/org for",
  "# GHCR). For public packages no registry credentials are required on the host.",
  "",
  "services:",
  "  app:",
  "    image: ghcr.io/OWNER/databento-discovery-mcp:latest",
  "    container_name: databento-discovery-mcp",
  "    restart: unless-stopped",
  "",
  "    ports:",
  '      - "0.0.0.0:8772:8772"',
  "",
  "    environment:",
  "      # Set your environment variables here or in a NAS-side .env file",
  "      # (genproj never commits secrets). See .env.example.",
  "      DATABENTO_API_KEY: ${DATABENTO_API_KEY}",
  "    labels:",
  '      - "com.centurylinklabs.watchtower.enable=true"',
  '      - "homepage.group=Services"',
  '      - "homepage.name=databento-discovery-mcp"',
  '      - "homepage.href=http://nas:8772/"',
  '      - "homepage.widget.type=customapi"',
  '      - "homepage.widget.url=http://localhost:8772/health"',
  '      - "homepage.widget.mappings[0].field=status"',
  '      - "homepage.widget.mappings[0].label=Status"',
  "",
].join("\n");

describe("docker-container externalNetworks: strictly additive", () => {
  it("is byte-identical to the pre-feature compose when unset", async () => {
    const compose = byPath(await generate(), "docker-compose.yml");
    expect(compose.content).toBe(BASELINE_COMPOSE);
  });

  it("is byte-identical between an absent field and an explicit empty array", async () => {
    const absent = byPath(await generate(), "docker-compose.yml").content;
    const empty = byPath(
      await generate({ externalNetworks: [] }),
      "docker-compose.yml",
    ).content;
    expect(empty).toBe(absent);
  });

  it("emits no networks key (and no empty mapping) by default", async () => {
    const compose = byPath(await generate(), "docker-compose.yml");
    expect(compose.content).not.toContain("networks");
  });

  it("leaves deploy/README.md byte-identical when unset", async () => {
    const readme = byPath(await generate(), "deploy/README.md").content;
    // The external-network bullet is the only prose the feature adds, and it is
    // appended inline, so with no external networks the README must not move.
    expect(readme).not.toContain("External networks");
    expect(readme).toContain("- Network mode is `bridge`.\n");
  });
});

describe("docker-container externalNetworks: emission", () => {
  it("attaches the service and declares the network external: true", async () => {
    const compose = byPath(
      await generate({ externalNetworks: ["ai_proxy"] }),
      "docker-compose.yml",
    );

    expect(compose.content).toContain(
      "    networks:\n      - ai_proxy\nnetworks:\n  ai_proxy:\n    external: true\n",
    );
    // The service block still carries the port binding (bridge mode).
    expect(compose.content).toContain('      - "0.0.0.0:8772:8772"');
    expect(compose.content).not.toContain("network_mode");
  });

  it("emits a compose file that parses as valid YAML", async () => {
    const YAML = await import("yaml");
    const compose = byPath(
      await generate({ externalNetworks: ["ai_proxy"] }),
      "docker-compose.yml",
    );

    const doc = YAML.parse(compose.content);
    expect(doc.services.app.networks).toEqual(["ai_proxy"]);
    expect(doc.networks).toEqual({ ai_proxy: { external: true } });
    // No accidental self-declaration that Compose would try to create.
    expect(doc.networks.ai_proxy.external).toBe(true);
  });

  it("preserves declaration order across multiple networks", async () => {
    const YAML = await import("yaml");
    const compose = byPath(
      await generate({ externalNetworks: ["ai_proxy", "backend", "metrics"] }),
      "docker-compose.yml",
    );

    const doc = YAML.parse(compose.content);
    expect(doc.services.app.networks).toEqual([
      "ai_proxy",
      "backend",
      "metrics",
    ]);
    expect(Object.keys(doc.networks)).toEqual([
      "ai_proxy",
      "backend",
      "metrics",
    ]);
  });

  it("drops blanks and trims whitespace in the declared names", async () => {
    const YAML = await import("yaml");
    const compose = byPath(
      await generate({ externalNetworks: ["  ai_proxy  ", "", "   "] }),
      "docker-compose.yml",
    );

    const doc = YAML.parse(compose.content);
    expect(doc.services.app.networks).toEqual(["ai_proxy"]);
  });

  it("is a pure function of the capability SET, not its order", async () => {
    const forward = await generateAllFiles({
      name: "databento-discovery-mcp",
      capabilities: ["docker-container", "devcontainer-python"],
      configuration: {
        "docker-container": { ...BASE_CONFIG, externalNetworks: ["ai_proxy"] },
      },
    });
    const reversed = await generateAllFiles({
      name: "databento-discovery-mcp",
      capabilities: ["devcontainer-python", "docker-container"],
      configuration: {
        "docker-container": { ...BASE_CONFIG, externalNetworks: ["ai_proxy"] },
      },
    });

    expect(byPath(reversed, "docker-compose.yml").content).toBe(
      byPath(forward, "docker-compose.yml").content,
    );
  });

  it("documents the external network in deploy/README.md", async () => {
    const readme = byPath(
      await generate({ externalNetworks: ["ai_proxy"] }),
      "deploy/README.md",
    ).content;

    expect(readme).toContain("## 6. Networking notes");
    expect(readme).toContain(
      "External networks: this service joins `ai_proxy`",
    );
    // The consequence that matters six months later: the compose file is
    // generated, so a hand-added network block is overwritten.
    expect(readme).toMatch(/hand is overwritten on regeneration/);
    expect(readme).toContain("`externalNetworks` configuration");
  });
});

describe("docker-container externalNetworks: host-mode interaction", () => {
  it("rejects networkMode host together with external networks", async () => {
    await expect(
      generate({ networkMode: "host", externalNetworks: ["ai_proxy"] }),
    ).rejects.toThrow(/networkMode "host".*externalNetworks/s);
  });

  it("throws a ValidationError naming the field", () => {
    expect(() =>
      validateDockerNetworks({
        capabilities: ["docker-container"],
        configuration: {
          "docker-container": {
            networkMode: "host",
            externalNetworks: ["ai_proxy"],
          },
        },
      }),
    ).toThrow(ValidationError);
  });

  it("ignores the combination when docker-container is not selected", () => {
    expect(() =>
      validateDockerNetworks({
        capabilities: ["devcontainer-python"],
        configuration: {
          "docker-container": {
            networkMode: "host",
            externalNetworks: ["ai_proxy"],
          },
        },
      }),
    ).not.toThrow();
  });

  // Defence in depth: an unauthenticated preview does not run the guards, so
  // the template-data builder itself must never produce both keys.
  it("suppresses the emission under host mode in template data", () => {
    const data = getCapabilityTemplateData("docker-container", {
      capabilities: ["docker-container", "devcontainer-python"],
      projectName: "sample-app",
      configuration: {
        "docker-container": {
          networkMode: "host",
          externalNetworks: ["ai_proxy"],
        },
      },
    });

    expect(data.networkModeLine).toContain("network_mode: host");
    expect(data.composeNetworks).toBe("");
    expect(data.externalNetworksDocs).toBe("");
  });

  it("exposes the networks through template data in bridge mode", () => {
    const data = getCapabilityTemplateData("docker-container", {
      capabilities: ["docker-container", "devcontainer-python"],
      projectName: "sample-app",
      configuration: {
        "docker-container": { externalNetworks: ["ai_proxy"] },
      },
    });

    expect(data.composeNetworks).toBe(
      "    networks:\n      - ai_proxy\nnetworks:\n  ai_proxy:\n    external: true",
    );
    expect(data.externalNetworksDocs).toContain(
      "this service joins `ai_proxy`",
    );
  });
});
